services:
  db:
    image: postgres:15
    container_name: bitkabirgateway
    environment:
      POSTGRES_USER: kabir
      POSTGRES_PASSWORD: kabir
      POSTGRES_DB: bitkabirgateway
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U kabir"]
      interval: 5s
      retries: 10
      start_period: 5s

  api:
    container_name: integration_kabir
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    command: npm run start:dev
    ports:
      - "3000:3000"
      - "4000:4000"
      - "9222:9222"

    # environment:
    #   DATABASE_URL: "postgresql://kabir:kabir@db:5432/bitkabirgateway?schema=public"
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    restart: unless-stopped

volumes:
  dbdata:
  node_modules: